xyz/openbmc_project/Ipmi/Internal/server.cpp: ${srcdir}/../xyz/openbmc_project/Ipmi/Internal/SoftPowerOff.interface.yaml xyz/openbmc_project/Ipmi/Internal/SoftPowerOff/server.hpp
	@mkdir -p `dirname $@`
	$(SDBUSPLUSPLUS) -r $(top_srcdir) interface server-cpp xyz.openbmc_project.Ipmi.Internal.SoftPowerOff > $@

xyz/openbmc_project/Ipmi/Internal/SoftPowerOff/server.hpp: ${top_srcdir}/xyz/openbmc_project/Ipmi/Internal/SoftPowerOff.interface.yaml
	@mkdir -p `dirname $@`
	$(SDBUSPLUSPLUS) -r $(top_srcdir) interface server-header xyz.openbmc_project.Ipmi.Internal.SoftPowerOff > $@

server_dbus_cpp_SOURCES = \
	xyz/openbmc_project/Ipmi/Internal/server.cpp

server_dbus_hpp_SOURCES = \
	xyz/openbmc_project/Ipmi/Internal/SoftPowerOff/server.hpp

server_dbus.cpp: $(server_dbus_cpp_SOURCES)
server_dbus.hpp: $(server_dbus_hpp_SOURCES)

nodist_include_HEADERS = $(server_dbus.hpp)

.PHONY: clean-dbus
clean-dbus:
	for i in $(server_dbus_cpp_SOURCES) \
	         $(server_dbus_hpp_SOURCES); \
	do \
	    test -e $$i && rm $$i ; \
	    test -d `dirname $$i` && rmdir -p `dirname $$i` ; \
	    true; \
	done
